name: javidcoffee_web_app
description: "A new Flutter project."
version: 1.0.0

environment:
  sdk: ^3.6.0-149.3.beta

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dotenv: ^4.2.0
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.0
  supabase: ^2.5.0
  supabase_flutter: ^2.8.0
  flutter_dotenv: ^5.2.1
  app_links: ^6.3.2
  appcheck: ^1.5.2
  safe_device: ^1.1.9
  screen_protector: ^1.4.2+1
  curved_navigation_bar: ^1.0.6
  lottie: ^3.1.3
  connectivity_plus: ^6.1.0
  carousel_slider: ^5.0.0
  icons_launcher: ^3.0.0
  flutter_svg: ^2.0.16
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  animate_do: ^3.3.4
  gradient_borders: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/icon/
    - assets/images/
    - assets/animations/
    - .env

  fonts:
    - family: IranianSans
      fonts:
        - asset: assets/fonts/IranianSans.ttf
    - family: B_Koodak_Bold_0
      fonts:
        - asset: assets/fonts/B_Koodak_Bold_0.ttf
    - family: B_Koodak_Outline_0
      fonts:
        - asset: assets/fonts/B_Koodak_Outline_0.ttf
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazir.ttf
    - family: Yekan
      fonts:
        - asset: assets/fonts/Yekan.ttf

icons_launcher:
  image_path: "assets/icon/AppIcon.jpeg"
  platforms:
    android:
      enable: true
      image_path: "assets/icon/AppIcon.jpeg"
      notification_image: "assets/icon/AppIcon.jpeg"
      adaptive_background_image: "assets/icon/AppIcon.jpeg"
      adaptive_foreground_image: "assets/icon/AppIcon.jpeg"
      adaptive_round_image: "assets/icon/AppIcon.jpeg"
      adaptive_monochrome_image: "assets/icon/AppIcon.jpeg"
    ios:
      enable: true
      image_path: "assets/icon/AppIcon.jpeg"
      dark_path: "assets/icon/AppIcon.jpeg"
      tinted_path: "assets/icon/AppIcon.jpeg"
    web:
      enable: true
      image_path: "assets/icon/AppIcon.jpeg"
      favicon_path: "assets/icon/AppIcon.jpeg"
    macos:
      enable: false
      image_path: "assets/icon/AppIcon.jpeg"
    windows:
      enable: false
      image_path: "assets/icon/AppIcon.jpeg"
    linux:
      enable: false
      image_path: "assets/icon/AppIcon.jpeg"
